from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

from dashboard.mock.service import predict


SCENARIOS_PATH = Path(__file__).resolve().parents[2] / "dashboard" / "mock" / "scenarios.json"


def tool_read_model_output(payload: Dict[str, Any]) -> Dict[str, Any]:
    return predict(payload)


def tool_read_policy() -> Dict[str, Any]:
    with SCENARIOS_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def tool_dashboard_explainer(risk_level: str, risk_score: float) -> str:
    return f"Decision generated by agent layer: {risk_level} risk with score {risk_score:.1f}/100."
